export { ContentBlock } from "./content/block";
export { BurgerMenu } from "./nav/BurgerMenu";
export { Slider } from "./slider/slider";
export * from "./shared/layout";
export { MainHeader } from "./header/header";
export { AboutUs } from "./aboutUs/aboutUs";
export { OurFood } from "./ourFood/ourFood";
export { FoodMenu } from "./FoodMenu/foodMenu";
export { Reviews } from "./reviews/reviews";
export { Contact } from "./contact/contact";
